// Modules
// This variable is for tracking all the modules that are used in our pathways. It is an array of objects that have the following structure
// {
//   length: Number(minutes),
//   title: String,
//   description: String,
//   id: String, // These are module codes constructed depending on the capability and level
//   resources: Array(Object({ name: String, description: String, link: String })), // This is a map of the resources associated with the module - ususlly external links
//   tags: Array(String), // List of tags associated with a module
//   capability: String, // ID of the capability it is associated with
//   level: String, // ID of the level that the module is in
// }

const modules = [
  {
    length: '',
    title: 'Deploying Mobile Apps',
    description: '',
    id: 'DEPLL1003',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['mobile', 'application', 'deploy'],
    capability: 'DEPL',
    level: 'L1',
  },
  {
    length: '',
    title: 'Deploying Web Apps',
    description: '',
    id: 'DEPLL1002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['web', 'application', 'deploy'],
    capability: 'DEPL',
    level: 'L1',
  },
  {
    length: '',
    title: 'The Power of Templating',
    description: '',
    id: 'DEPLL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['deploy', 'templating', 'principles'],
    capability: 'DEPL',
    level: 'L1',
  },
  {
    length: '',
    title: 'Managing App deployments with Helm',
    description: '',
    id: 'DEPLL2002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['deploy', 'web', 'helm', 'applications'],
    capability: 'DEPL',
    level: 'L2',
  },
  {
    length: '',
    title: 'Deployment Strategies to minimise customer impact',
    description: '',
    id: 'DEPLL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['principles', 'deploy', 'production'],
    capability: 'DEPL',
    level: 'L2',
  },
  {
    length: '',
    title: 'Production Ready Helm Charts',
    description: '',
    id: 'DEPLL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['deploy', 'production', 'helm'],
    capability: 'DEPL',
    level: 'L3',
  },
  {
    length: '',
    title: 'Building robust systems of deployment',
    description: '',
    id: 'DEPLL4001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['deploy', 'production', 'principles'],
    capability: 'DEPL',
    level: 'L4',
  },
  {
    length: '',
    title: 'Multi environment and multi app charts',
    description: '',
    id: 'DEPLL4002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['deploy', 'helm'],
    capability: 'DEPL',
    level: 'L4',
  },
  {
    length: '',
    title: 'Building environments for multiple deployments per day',
    description: '',
    id: 'DEPLL5001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['deploy', 'principles'],
    capability: 'DEPL',
    level: 'L5',
  },
  {
    length: '',
    title: 'Reporting & dashboard',
    description: '',
    id: 'TSTAL3002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['test', 'reporting'],
    capability: 'TSTA',
    level: 'L3',
  },
  {
    length: '',
    title: 'DevOps Test Suites',
    description: '',
    id: 'TSTAL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['test', 'suites'],
    capability: 'TSTA',
    level: 'L3',
  },
  {
    length: '',
    title: 'Automated tests',
    description: '',
    id: 'TSTAL4001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['test', 'automation'],
    capability: 'TSTA',
    level: 'L4',
  },
  {
    length: '',
    title: 'Designing your system for NFRs',
    description: '',
    id: 'PNFRL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['production', 'nfr', 'system'],
    capability: 'PNFR',
    level: 'L2',
  },
  {
    length: '',
    title: 'Performance and Penetration testing from the start',
    description: '',
    id: 'PNFRL2002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['production', 'nfr', 'performance', 'penetration'],
    capability: 'PNFR',
    level: 'L2',
  },
  {
    length: '',
    title: 'Creating chaos systems',
    description: '',
    id: 'PNFRL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['production', 'nfr', 'chaos'],
    capability: 'PNFR',
    level: 'L3',
  },
  {
    length: '',
    title: 'Managing Secrets and API keys securely',
    description: '',
    id: 'COMPL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['complience', 'secrets', 'keys'],
    capability: 'COMP',
    level: 'L1',
  },
  {
    length: '',
    title: 'IAM Policy',
    description: '',
    id: 'COMPL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['complience', 'iam'],
    capability: 'COMP',
    level: 'L2',
  },
  {
    length: '',
    title: 'RBAC',
    description: '',
    id: 'COMPL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['complience', 'rbac'],
    capability: 'COMP',
    level: 'L3',
  },
  {
    length: '',
    title: 'Designing system according to regulation',
    description: '',
    id: 'COMPL4001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['complience', 'regulation', 'systmes'],
    capability: 'COMP',
    level: 'L4',
  },
  {
    length: '',
    title: 'Ansible basics',
    description: '',
    id: 'CONFL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['ansible', 'config'],
    capability: 'CONF',
    level: 'L1',
  },
  {
    length: '',
    title: 'Bootstrapping',
    description: '',
    id: 'CONFL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['config', 'ansible', 'bootstrap'],
    capability: 'CONF',
    level: 'L2',
  },
  {
    length: '',
    title: 'Hardening',
    description: '',
    id: 'CONFL2002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['config', 'ansible', 'hardening'],
    capability: 'CONF',
    level: 'L2',
  },
  {
    length: '',
    title: 'Ansible Tower and Galaxy',
    description: '',
    id: 'CONFL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['config', 'ansible', 'tower', 'galaxy'],
    capability: 'CONF',
    level: 'L3',
  },
  {
    length: '',
    title: 'Writing Ansible Custom Modules',
    description: '',
    id: 'CONFL5001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['config', 'ansible', 'modules'],
    capability: 'CONF',
    level: 'L5',
  },
  {
    length: '',
    title: 'Mapping branches to environments',
    description: '',
    id: 'RELEL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['release', 'branches', 'environments', 'git'],
    capability: 'RELE',
    level: 'L1',
  },
  {
    length: '',
    title: 'Release package management',
    description: '',
    id: 'RELEL1003',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['release', 'package'],
    capability: 'RELE',
    level: 'L1',
  },
  {
    length: '',
    title: 'Using Git tags for marking versions',
    description: '',
    id: 'RELEL1002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['release', 'git', 'tags'],
    capability: 'RELE',
    level: 'L1',
  },
  {
    length: '',
    title: 'Artifactory',
    description: '',
    id: 'RELEL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['release', 'artifactory'],
    capability: 'RELE',
    level: 'L2',
  },
  {
    length: '',
    title: 'Automated Creation of Release Notes',
    description: '',
    id: 'RELEL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['release', 'notes', 'automation'],
    capability: 'RELE',
    level: 'L3',
  },
  {
    length: '',
    title: 'Developing fully integrated release processes',
    description: '',
    id: 'RELEL4001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['release', 'automation', 'process', 'deploy'],
    capability: 'RELE',
    level: 'L4',
  },
  {
    length: '',
    title: 'Networking Basics: whats are the concepts',
    description: '',
    id: 'NETWL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['networking', 'basics', 'principles'],
    capability: 'NETW',
    level: 'L1',
  },
  {
    length: '',
    title: 'VPCs, Subnets and DMZs',
    description: '',
    id: 'NETWL1002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['networking', 'vpc', 'subnet'],
    capability: 'NETW',
    level: 'L1',
  },
  {
    length: '',
    title: 'Understanding how data flows through your architecture',
    description: '',
    id: 'NETWL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['networking', 'data', 'flow', 'architecture'],
    capability: 'NETW',
    level: 'L2',
  },
  {
    length: '',
    title: 'Proxies, Cloudflare, DNS and other layers',
    description: '',
    id: 'NETWL2002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['networking', 'proxies', 'dns'],
    capability: 'NETW',
    level: 'L2',
  },
  {
    length: '',
    title: 'Security Groups, ACLs, Firewalls',
    description: '',
    id: 'NETWL2003',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['networking', 'firewalls', 'security', 'acl'],
    capability: 'NETW',
    level: 'L2',
  },
  {
    length: '',
    title: 'Network Protocols',
    description: '',
    id: 'NETWL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['networking', 'protocols'],
    capability: 'NETW',
    level: 'L3',
  },
  {
    length: '',
    title: 'Terraform Basics',
    description: '',
    id: 'INCOL1002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['infrastructure', 'code', 'basics'],
    capability: 'INCO',
    level: 'L1',
  },
  {
    length: '',
    title: 'Best Practices for Writing Infrastructure as Code',
    description: '',
    id: 'INCOL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['infrastructure', 'code', 'principles'],
    capability: 'INCO',
    level: 'L1',
  },
  {
    length: '',
    title: 'Advanced Terraform and writing modular code',
    description: '',
    id: 'INCOL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['infrastructure', 'code', 'modules'],
    capability: 'INCO',
    level: 'L3',
  },
  {
    length: '',
    title: 'CloudFormation (AWS)',
    description: '',
    id: 'INCOL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['infrastructure', 'code', 'cloudformation', 'aws'],
    capability: 'INCO',
    level: 'L2',
  },
  {
    length: '',
    title: 'Powershell (Azure)',
    description: '',
    id: 'INCOL2002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['infrastructure', 'code', 'powershell', 'azure'],
    capability: 'INCO',
    level: 'L2',
  },
  {
    length: '',
    title: 'Using Terraform and Ansible together',
    description: '',
    id: 'INCOL3002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['infrastructure', 'code', 'ansible', 'automation'],
    capability: 'INCO',
    level: 'L3',
  },
  {
    length: '',
    title: 'Principles of CICD',
    description: '',
    id: 'CICDL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['cicd', 'automation', 'principles'],
    capability: 'CICD',
    level: 'L1',
  },
  {
    length: '',
    title: 'Thinking like an Automator',
    description: '',
    id: 'CICDL1002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['cicd', 'automation', 'principles'],
    capability: 'CICD',
    level: 'L1',
  },
  {
    length: '',
    title: 'Tekton Basics',
    description: '',
    id: 'CICDL2004',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['cicd', 'automation', 'tekton', 'basics'],
    capability: 'CICD',
    level: 'L2',
  },
  {
    length: '',
    title: 'Jenkins basics',
    description: '',
    id: 'CICDL2003',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['cicd', 'automation', 'jenkins', 'basics'],
    capability: 'CICD',
    level: 'L2',
  },
  {
    length: '',
    title: 'Azure DevOps basics',
    description: '',
    id: 'CICDL2002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['cicd', 'automation', 'azure', 'basics'],
    capability: 'CICD',
    level: 'L2',
  },
  {
    length: '',
    title: 'Introduction to other CICD tooling',
    description: '',
    id: 'CICDL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['cicd', 'automation', 'tools'],
    capability: 'CICD',
    level: 'L2',
  },
  {
    length: '',
    title: 'Advanced Jenkins',
    description: '',
    id: 'CICDL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['cicd', 'automation', 'jenkins', 'advanced'],
    capability: 'CICD',
    level: 'L3',
  },
  {
    length: '',
    title: 'Jenkinsfiles and Groovy scripting',
    description: '',
    id: 'CICDL3002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['cicd', 'automation', 'jenkins', 'groovy'],
    capability: 'CICD',
    level: 'L3',
  },
  {
    length: '',
    title: 'Advanced Tekton and constructing modular tasks',
    description: '',
    id: 'CICDL4001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['cicd', 'automation', 'tekton', 'modules'],
    capability: 'CICD',
    level: 'L4',
  },
  {
    length: '',
    title: 'Jenkins Shared Libraries and repeatable code',
    description: '',
    id: 'CICDL4002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['cicd', 'automation', 'library', 'repeatable'],
    capability: 'CICD',
    level: 'L4',
  },
  {
    length: '',
    title: 'Develop complex CICD automation: build, test, deploy',
    description: '',
    id: 'CICDL5001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['cicd', 'automation', 'system'],
    capability: 'CICD',
    level: 'L5',
  },
  {
    length: '',
    title: 'Bash scripting and using terminal',
    description: '',
    id: 'LANGL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['languages', 'bash', 'terminal'],
    capability: 'LANG',
    level: 'L1',
  },
  {
    length: '',
    title: '+1 Language of choice',
    description: '',
    id: 'LANGL1002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['languages'],
    capability: 'LANG',
    level: 'L1',
  },
  {
    length: '',
    title: 'Python Basics',
    description: '',
    id: 'LANGL1003',
    resources: [
      {
        name: 'Complete Python Masterclass',
        description: '',
        link:
          'www.udemy.com/course/python-the-complete-python-developer-course/',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['languages', 'python', ''],
    capability: 'LANG',
    level: 'L1',
  },
  {
    length: '',
    title: 'Understanding test driven development',
    description: '',
    id: 'LANGL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['languages', 'development', 'test'],
    capability: 'LANG',
    level: 'L2',
  },
  {
    length: '',
    title: 'Develop simple apps in at least one language',
    description: '',
    id: 'LANGL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['languages', 'applications', 'basics'],
    capability: 'LANG',
    level: 'L3',
  },
  {
    length: '',
    title: 'Develop complex apps in at least one language',
    description: '',
    id: 'LANGL5001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['languages', 'advanced', 'applications'],
    capability: 'LANG',
    level: 'L5',
  },
  {
    length: '',
    title: 'Docker Basics and Container Architecture',
    description: '',
    id: 'CONTL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['containers', 'docker', 'basics', 'architecture'],
    capability: 'CONT',
    level: 'L1',
  },
  {
    length: '',
    title: 'Podman Basics',
    description: '',
    id: 'CONTL1002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['containers', 'podman', 'basics'],
    capability: 'CONT',
    level: 'L1',
  },
  {
    length: '',
    title: 'Container security',
    description: '',
    id: 'CONTL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['containers', 'security'],
    capability: 'CONT',
    level: 'L2',
  },
  {
    length: '',
    title: 'Docker Multi Stage builer and using small app images',
    description: '',
    id: 'CONTL2002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['containers', 'docker', 'builder', 'applications'],
    capability: 'CONT',
    level: 'L2',
  },
  {
    length: '',
    title: 'Using containers as production packages',
    description: '',
    id: 'CONTL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['containers', 'docker', 'production'],
    capability: 'CONT',
    level: 'L3',
  },
  {
    length: '',
    title: 'Kubernetes and Openshift Basics',
    description: '',
    id: 'COMGL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['containers', 'management', 'kubernetes', 'openshift'],
    capability: 'COMG',
    level: 'L1',
  },
  {
    length: '',
    title: 'Cluster architecture',
    description: '',
    id: 'COMGL1002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['containers', 'management', 'architecture'],
    capability: 'COMG',
    level: 'L1',
  },
  {
    length: '',
    title: 'Networking in and outside a cluster',
    description: '',
    id: 'COMGL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['containers', 'management', 'networking'],
    capability: 'COMG',
    level: 'L2',
  },
  {
    length: '',
    title: 'Deep dive into Kubernetes resources',
    description: '',
    id: 'COMGL2002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['containers', 'management', 'kubernetes', 'resources'],
    capability: 'COMG',
    level: 'L2',
  },
  {
    length: '',
    title: 'Production ready configurations and considering NFRs',
    description: '',
    id: 'COMGL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['containers', 'management', 'production', 'nfr'],
    capability: 'COMG',
    level: 'L3',
  },
  {
    length: '',
    title: 'Provider Overview: Basics of each Provider',
    description:
      'To have a basic understanding of the offerings that each cloud provider has. Being able to give recommendation on cloud providers. At this level you are expected to achieve at least one cloud provider approved certification. (AWS/Azure/GCP)',
    id: 'CLODL1001',
    resources: [
      {
        name: 'Linux Academy Course: AWS Cloud Practitioner',
        description: '',
        link: 'linuxacademy.com/course/aws-cloud-practitioner-clf-c-01/#',
      },
      {
        name: 'Linux Academy Course: Azure Fundamentals',
        description: '',
        link:
          'linuxacademy.com/course/microsoft-azure-fundamentals-az-900-exam-prep/',
      },
      {
        name: 'Linux Academy Course: Google Cloud Essentials',
        description: '',
        link: 'linuxacademy.com/course/google-cloud-essentials/',
      },
      {
        name: 'AWS Learning Paths',
        description: '',
        link: 'aws.amazon.com/training/learning-paths/',
      },
      {
        name: 'AWS Cloud Practitioner Path',
        description: '',
        link: 'aws.amazon.com/training/path-cloudpractitioner/',
      },
      {
        name: 'Microsoft Azure Documentations',
        description: '',
        link: 'docs.microsoft.com/en-us/learn/azure/',
      },
      {
        name: 'Microsoft Azure Fundamentals Certification',
        description: '',
        link:
          'docs.microsoft.com/en-us/learn/certifications/azure-fundamentals',
      },
      {
        name: 'Google Cloud Training',
        description: '',
        link: 'cloud.google.com/training',
      },
      {
        name: 'Google Cloud Ceritification',
        description: '',
        link: 'cloud.google.com/certification/gsuite',
      },
    ],
    tags: ['cloud', 'certification', 'azure', 'gcp', 'aws'],
    capability: 'CLOD',
    level: 'L1',
  },
  {
    length: '',
    title: 'Provider Overview: What distinguishes each',
    description:
      'Having the knowledge to clearly distinguish the differences between the products on offer for each cloud provider. Having a working knowledge of how networking and fundamental products work for each cloud provider.',
    id: 'CLODL1002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['cloud', 'providers'],
    capability: 'CLOD',
    level: 'L1',
  },
  {
    length: '',
    title: 'Cloud Specialist: Service offerings and how it works',
    description:
      'Having a clear understanding on one/multiple cloud offerings and being able to work with said cloud provider (AWS/Azure/GCP). At this level you are expected to achieve at least one Associate level cloud provider certification for level 2 and at least two certification for level 3.',
    id: 'CLODL3001',
    resources: [
      {
        name: 'AWS Learning Paths',
        description: '',
        link: 'aws.amazon.com/training/learning-paths/',
      },
      {
        name: 'AWS DevOps Certification',
        description: '',
        link: 'aws.amazon.com/training/path-devops/',
      },
      {
        name: 'Microsoft Azure Documentation',
        description: '',
        link: 'docs.microsoft.com/en-us/learn/azure/',
      },
      {
        name: 'Microsoft Azure DevOps Engineer',
        description: '',
        link:
          'docs.microsoft.com/en-us/learn/certifications/roles/devops-engineer',
      },
      {
        name: 'Google Cloud Training',
        description: '',
        link: 'cloud.google.com/training',
      },
      {
        name: 'Google Cloud Engineer Pathway',
        description: '',
        link: 'cloud.google.com/certification/cloud-engineer',
      },
    ],
    tags: ['cloud', 'certification', 'aws', 'azure', 'gcp'],
    capability: 'CLOD',
    level: 'L3',
  },
  {
    length: '',
    title: 'Solutioning for the Cloud',
    description:
      'Being able to design and build infrastructure for clients in a chosen/all cloud providers. Clearly demonstrating working knowledge of the products available and optimising for the clients needs.',
    id: 'CLODL4001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['cloud', 'solutioning', ''],
    capability: 'CLOD',
    level: 'L4',
  },
  {
    length: '',
    title: 'Cloud Specialist: Deep knowledge of a cloud provider',
    description:
      'Becoming an SME in cloud technologies, what products to use and how to use them. At this level you are expected to achieve a professional level cloud provider certification in at least one cloud (AWS/Azure/GCP)',
    id: 'CLODL5001',
    resources: [
      {
        name: 'AWS Learning Paths',
        description: '',
        link: 'aws.amazon.com/training/learning-paths/',
      },
      {
        name: 'AWS DevOps Certification',
        description: '',
        link: 'aws.amazon.com/training/path-devops/',
      },
      {
        name: 'Microsoft Azure Documentation',
        description: '',
        link: 'docs.microsoft.com/en-us/learn/azure/',
      },
      {
        name: 'Microsoft Azure Solutions Architect',
        description: '',
        link:
          'https://docs.microsoft.com/en-us/learn/certifications/azure-solutions-architect',
      },
      {
        name: 'Google Cloud Training',
        description: '',
        link: 'cloud.google.com/training',
      },
      {
        name: 'Google Cloud Engineer Pathway',
        description: '',
        link: 'cloud.google.com/certification/cloud-engineer',
      },
    ],
    tags: ['cloud', '', ''],
    capability: 'CLOD',
    level: 'L5',
  },
  {
    length: '',
    title: 'Working with Cloud Infrastructure',
    description: '',
    id: 'ARCHL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['architecture', 'solutioning', 'cloud', 'infrastructure'],
    capability: 'ARCH',
    level: 'L3',
  },
  {
    length: '',
    title: 'Architecting Apps for Security, NFRs and production systems',
    description: '',
    id: 'ARCHL3002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['architecture', 'solutioning', 'nfr', 'security'],
    capability: 'ARCH',
    level: 'L3',
  },
  {
    length: '',
    title: 'Converting business objectives to cloud native solutions',
    description: '',
    id: 'ARCHL4001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['architecture', 'solutioning', 'business', 'cloud'],
    capability: 'ARCH',
    level: 'L4',
  },
  {
    length: '',
    title: 'Understanding the full tech stack to design solutions',
    description: '',
    id: 'ARCHL5001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['architecture', 'solutioning', 'principle'],
    capability: 'ARCH',
    level: 'L5',
  },
  {
    length: '',
    title: 'Intro to tooling: what to use and when?',
    description: '',
    id: 'MONIL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['monitoring', 'dashboards', 'basics', 'tools'],
    capability: 'MONI',
    level: 'L1',
  },
  {
    length: '',
    title: 'Slack notifications for pipeline monitoring',
    description: '',
    id: 'MONIL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['monitoring', 'dashboards', 'slack', 'notifications'],
    capability: 'MONI',
    level: 'L2',
  },
  {
    length: '',
    title: 'Istio, service mesh and Consul',
    description: '',
    id: 'MONIL2002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['monitoring', 'dashboards', 'istio', 'networking'],
    capability: 'MONI',
    level: 'L2',
  },
  {
    length: '',
    title: 'Automated actions from triggers and alerts in infrastructure',
    description: '',
    id: 'MONIL2003',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['monitoring', 'dashboards', 'istio', 'networking'],
    capability: 'MONI',
    level: 'L2',
  },
  {
    length: '',
    title: 'Advanced Monitoring: Creating dashboards and mining logs',
    description: '',
    id: 'MONIL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['monitoring', 'dashboards', 'logging'],
    capability: 'MONI',
    level: 'L3',
  },
  {
    length: '',
    title: 'ElasticStack',
    description: '',
    id: 'MONIL3002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['monitoring', 'dashboards', 'elasticstack'],
    capability: 'MONI',
    level: 'L3',
  },
  {
    length: '',
    title: 'Splunk and Dynatrace',
    description: '',
    id: 'MONIL3003',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['monitoring', 'dashboards', 'splunk', 'dynatrace'],
    capability: 'MONI',
    level: 'L3',
  },
  {
    length: '',
    title: 'How to think like a DevOps engineer?',
    description: '',
    id: 'CONSL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['consultancy', 'client', 'devops'],
    capability: 'CONS',
    level: 'L1',
  },
  {
    length: '',
    title: 'Understanding your role as a DevOps engineer',
    description: '',
    id: 'CONSL1002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['consultancy', 'client', 'role'],
    capability: 'CONS',
    level: 'L1',
  },
  {
    length: '',
    title: 'Presentation and Demo Skills',
    description: '',
    id: 'CONSL1003',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['consultancy', 'client', 'presentation', 'demo'],
    capability: 'CONS',
    level: 'L1',
  },
  {
    length: '',
    title: 'Defining the goals of DevOps on Projects',
    description: '',
    id: 'CONSL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['consultancy', 'client', 'goals', 'devops'],
    capability: 'CONS',
    level: 'L2',
  },
  {
    length: '',
    title: 'Becoming a Pro DevOps Engineer',
    description: '',
    id: 'CONSL2002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['consultancy', 'client', 'pro', 'devops'],
    capability: 'CONS',
    level: 'L2',
  },
  {
    length: '',
    title: 'Client Project Experience',
    description: '',
    id: 'CONSL4001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['consultancy', 'client'],
    capability: 'CONS',
    level: 'L4',
  },
  {
    length: '',
    title: 'Leadership roles in Client Projects',
    description: '',
    id: 'CONSL5001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['consultancy', 'client'],
    capability: 'CONS',
    level: 'L5',
  },
  {
    length: '',
    title: 'Git basics',
    description: '',
    id: 'SCMGL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['scm', 'git', 'basics'],
    capability: 'SCMG',
    level: 'L1',
  },
  {
    length: '',
    title: 'Git Branching Strategies',
    description: '',
    id: 'SCMGL1002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['scm', 'git', 'branching', 'strategy'],
    capability: 'SCMG',
    level: 'L1',
  },
  {
    length: '',
    title: 'Enabling Continuous Development',
    description: '',
    id: 'SCMGL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['scm', 'git', 'continuous', 'development'],
    capability: 'SCMG',
    level: 'L2',
  },
  {
    length: '',
    title: 'Advanced Git Commands: Improve your workflow',
    description: '',
    id: 'SCMGL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['scm', 'git', 'advanced'],
    capability: 'SCMG',
    level: 'L3',
  },
  {
    length: '',
    title: 'Scaled Git workflows for multiple development teams',
    description: '',
    id: 'SCMGL3002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['scm', 'git', 'scaled'],
    capability: 'SCMG',
    level: 'L3',
  },
  {
    length: '',
    title: 'Security basics',
    description: '',
    id: 'SECUL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['security', 'basics'],
    capability: 'SECU',
    level: 'L1',
  },
  {
    length: '',
    title: 'Encryption, keys and tokens',
    description: '',
    id: 'SECUL1002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['security', 'encryption', 'keys', 'tokens'],
    capability: 'SECU',
    level: 'L1',
  },
  {
    length: '',
    title: 'Secret Management in CICD and IaC',
    description: '',
    id: 'SECUL1003',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['security', 'cicd', 'iac'],
    capability: 'SECU',
    level: 'L1',
  },
  {
    length: '',
    title: 'How to introduce security from the start',
    description: '',
    id: 'SECUL2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['security', 'principles'],
    capability: 'SECU',
    level: 'L2',
  },
  {
    length: '',
    title: 'Vulnerability scanning',
    description: '',
    id: 'SECUL2002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['security', 'vulnerability'],
    capability: 'SECU',
    level: 'L2',
  },
  {
    length: '',
    title: 'Linting and Code Quality',
    description: '',
    id: 'SECUL2003',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['security', 'linting'],
    capability: 'SECU',
    level: 'L2',
  },
  {
    length: '',
    title: 'SonarQube',
    description: '',
    id: 'SECUL3003',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['security', 'sonarqube', 'tools'],
    capability: 'SECU',
    level: 'L3',
  },
  {
    length: '',
    title: 'Getting Started with Security Test Applications',
    description: '',
    id: 'SECUL3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['security', 'principles', 'advanced'],
    capability: 'SECU',
    level: 'L3',
  },
  {
    length: '',
    title: 'Integrating security into pipelines and automation',
    description: '',
    id: 'SECUL3002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['security', 'principles', 'cicd'],
    capability: 'SECU',
    level: 'L3',
  },
  {
    length: '',
    title: 'Tips and tricks - working fast and efficiently',
    description: '',
    id: 'SYSML1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['system', 'basics'],
    capability: 'SYSM',
    level: 'L1',
  },
  {
    length: '',
    title: 'SysAdmin',
    description: '',
    id: 'SYSML2001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['system', 'admin'],
    capability: 'SYSM',
    level: 'L2',
  },
  {
    length: '',
    title: 'Text manipulation, process monitoring and networking',
    description: '',
    id: 'SYSML2002',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['system', 'text', 'monitoring', 'networking'],
    capability: 'SYSM',
    level: 'L2',
  },
  {
    length: '',
    title: 'Using vim: the remote text editor',
    description: '',
    id: 'SYSML2003',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['system', 'text'],
    capability: 'SYSM',
    level: 'L2',
  },
  {
    length: '',
    title: 'Working with Linux based OS',
    description: '',
    id: 'SYSML3001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['system', 'linux'],
    capability: 'SYSM',
    level: 'L2',
  },
  {
    length: '',
    title: 'The difference between SQL and NoSQL',
    description: '',
    id: 'DABAL1001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['database', 'sql', 'basics'],
    capability: 'DABA',
    level: 'L1',
  },
  {
    length: '',
    title: 'Big data management in complex systems',
    description: '',
    id: 'DABAL4001',
    resources: [
      {
        name: '',
        description: '',
        link: '',
      },
      {
        name: '',
        description: '',
        link: '',
      },
    ],
    tags: ['database', 'data'],
    capability: 'DABA',
    level: 'L4',
  },
];
